2024-11-23 03:16:24,052 - INFO - Training configuration:
2024-11-23 03:16:24,052 - INFO - num_points: 8192
2024-11-23 03:16:24,052 - INFO - chunk_size: 4096
2024-11-23 03:16:24,052 - INFO - overlap: 1024
2024-11-23 03:16:24,052 - INFO - batch_size: 64
2024-11-23 03:16:24,052 - INFO - num_workers: 0
2024-11-23 03:16:24,052 - INFO - learning_rate: 0.001
2024-11-23 03:16:24,052 - INFO - num_classes: 5
2024-11-23 03:16:24,052 - INFO - num_epochs: 500
2024-11-23 03:16:24,052 - INFO - device: cuda
2024-11-23 03:16:24,052 - INFO - Using device: cuda
2024-11-23 03:16:24,052 - INFO - Found 6 las files:
2024-11-23 03:16:24,052 - INFO - Loading data/fukushima/onepart/train/bridge-3.las
2024-11-23 03:16:24,493 - INFO - Loaded 16239683 points from bridge-3.las
2024-11-23 03:16:24,503 - INFO - Processing data - Points: (16239683, 3), Colors: (16239683, 3), Labels: (16239683,)
2024-11-23 03:16:35,145 - INFO - Created 6124 blocks
2024-11-23 03:16:35,330 - INFO - Loading data/fukushima/onepart/train/bridge-4.las
2024-11-23 03:16:35,653 - INFO - Loaded 12134787 points from bridge-4.las
2024-11-23 03:16:35,677 - INFO - Processing data - Points: (12134787, 3), Colors: (12134787, 3), Labels: (12134787,)
2024-11-23 03:16:43,592 - INFO - Created 4576 blocks
2024-11-23 03:16:43,711 - INFO - Loading data/fukushima/onepart/train/bridge-5.las
2024-11-23 03:16:43,941 - INFO - Loaded 8373599 points from bridge-5.las
2024-11-23 03:16:43,959 - INFO - Processing data - Points: (8373599, 3), Colors: (8373599, 3), Labels: (8373599,)
2024-11-23 03:16:49,679 - INFO - Created 9118 blocks
2024-11-23 03:16:49,782 - INFO - Loading data/fukushima/onepart/train/bridge-6.las
2024-11-23 03:16:50,120 - INFO - Loaded 12716121 points from bridge-6.las
2024-11-23 03:16:50,137 - INFO - Processing data - Points: (12716121, 3), Colors: (12716121, 3), Labels: (12716121,)
2024-11-23 03:16:58,855 - INFO - Created 5851 blocks
2024-11-23 03:16:58,984 - INFO - Loading data/fukushima/onepart/train/bridge-8.las
2024-11-23 03:16:59,535 - INFO - Loaded 20025746 points from bridge-8.las
2024-11-23 03:16:59,559 - INFO - Processing data - Points: (20025746, 3), Colors: (20025746, 3), Labels: (20025746,)
2024-11-23 03:17:12,696 - INFO - Created 4995 blocks
2024-11-23 03:17:12,877 - INFO - Loading data/fukushima/onepart/train/bridge-9.las
2024-11-23 03:17:13,602 - INFO - Loaded 26071676 points from bridge-9.las
2024-11-23 03:17:13,638 - INFO - Processing data - Points: (26071676, 3), Colors: (26071676, 3), Labels: (26071676,)
2024-11-23 03:17:31,956 - INFO - Created 7946 blocks
2024-11-23 03:17:32,281 - INFO - Total blocks created: 38610
2024-11-23 03:17:32,309 - INFO - reading train data
2024-11-23 03:17:32,309 - INFO - Found 1 las files:
2024-11-23 03:17:32,309 - INFO - Loading data/fukushima/onepart/val/bridge-7.las
2024-11-23 03:17:32,724 - INFO - Loaded 15021376 points from bridge-7.las
2024-11-23 03:17:32,733 - INFO - Processing data - Points: (15021376, 3), Colors: (15021376, 3), Labels: (15021376,)
2024-11-23 03:17:42,423 - INFO - Created 2213 blocks
2024-11-23 03:17:42,583 - INFO - Total blocks created: 2213
2024-11-23 03:17:42,599 - INFO - reading val data
2024-11-23 03:17:42,599 - INFO - Train dataset size: 38610
2024-11-23 03:17:42,599 - INFO - Val dataset size: 2213
2024-11-23 03:17:43,423 - INFO - Total samples is: <torch.utils.data.dataloader.DataLoader object at 0x000001E13BD64CB0>
2024-11-23 03:17:43,562 - ERROR - Training failed with exception:
Traceback (most recent call last):
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\train.py", line 321, in <module>
    train()
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\train.py", line 140, in train
    outputs = model(points, colors)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cy519\anaconda3\envs\pytorch\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cy519\anaconda3\envs\pytorch\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\models\model.py", line 41, in forward
    l1_xyz, l1_points = self.sa1(xyz, points)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cy519\anaconda3\envs\pytorch\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cy519\anaconda3\envs\pytorch\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\models\pointnet2_utils.py", line 122, in forward
    new_xyz, new_points = sample_and_group(self.npoint, self.radius, self.nsample, xyz, points)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\models\pointnet2_utils.py", line 44, in sample_and_group
    fps_idx = farthest_point_sample(xyz, npoint)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Work\Pointcloud-WL\Pointcloud-bridge\Highway_bridge\models\pointnet2_utils.py", line 73, in farthest_point_sample
    distance[mask] = dist[mask]
    ~~~~~~~~^^^^^^
RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Double for the source.
